# Site settings
title: Hacker Dungeon
email: ahmad@hackerdungeon.com
description: "Hackathons, workshops, and meetups"
baseurl: ""
url: "http://hackerdungeon.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
